services:
  db:
    image: postgres:16-alpine
    container_name: pg-aprendizado
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${APRENDIZADO_DB_DATABASE}
      POSTGRES_USER: ${APRENDIZADO_DB_USERNAME}
      POSTGRES_PASSWORD: ${APRENDIZADO_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kanban-server-network

  api:
    build: .
    container_name: aprendizado_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      APRENDIZADO_DB_URL: ${APRENDIZADO_DOCKER_DB_URL}
      APRENDIZADO_DB_USERNAME: ${APRENDIZADO_DB_USERNAME}
      APRENDIZADO_DB_PASSWORD: ${APRENDIZADO_DB_PASSWORD}
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET}
      API_SECURITY_TOKEN_ISSUER: ${API_SECURITY_TOKEN_ISSUER}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    networks:
      - kanban-server-network
      - apache-network # Conecta a API Kanban a REDE APACHE KAFKA

volumes:
  postgres_data:

networks:
  kanban-server-network:
    driver: bridge
  apache-network:
    external: true # Diz ao Docker para REUTILIZAR a rede existente do auth-server