spring.datasource.url=${APRENDIZADO_DB_URL}
spring.datasource.username=${APRENDIZADO_DB_USERNAME}
spring.datasource.password=${APRENDIZADO_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver