#Database
spring.datasource.url=${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
# Segredo partilhado com a API de Autenticação para validar o JWT
api.security.token.secret=${AUTH_JWT_SECRET}
api.security.token.issuer=${API_SECURITY_TOKEN_ISSUER}


# ============================================
# CONFIGURAÇÕES DO APACHE KAFKA (CONSUMER)
# ============================================

# Controle de ativação local
app.kafka.enabled=true

# Endereço dos brokers
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Consumer Group ID e estratégia de offset
spring.kafka.consumer.group-id=kanban-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# Deserializadores
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Mapeamento e pacotes confiáveis para o JSON Deserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.api.kanbam.domain.dtos.*
spring.kafka.consumer.properties.spring.json.type.mapping=userCreatedEvent:com.api.kanbam.domain.dtos.event.UserCreatedEventDTO

# Nome do Tópico
app.kafka.topics.user-created=user-created-topic
